export const ApiPath = {
  Health: '/healthz',
  Login: '/auth/login',
  Me: '/auth/me',
  Tenants: '/tenants/',
  TenantById: (id: string) => `/tenants/${id}`,
  CustomersRegister: '/customers/register',
  CustomerLogin: '/customers/login',
  CustomerGoogleLogin: '/customers/login/google',
  CustomerMe: '/customers/me',
  CustomerAppointments: '/customers/me/appointments',
  TenantBySlug: (slug: string) => `/tenants/by-slug/${slug}`,
  TenantMe: '/tenants/me',
  TenantWorkingHours: '/tenants/me/working-hours',
  Availability: '/availability',
  Users: '/users',
  Staff: '/staff',
  CatalogServices: '/catalog/services',
  Appointments: '/appointments',
  ConfirmAppointment: (id: string) => `/appointments/${id}/confirm`,
  CancelAppointment: (id: string) => `/appointments/${id}/cancel`,
  CompleteAppointment: (id: string) => `/appointments/${id}/complete`,
  NoShowAppointment: (id: string) => `/appointments/${id}/no-show`,
} as const;

export const HeaderName = {
  Authorization: 'Authorization',
  ContentType: 'Content-Type',
  TenantId: 'X-Tenant-ID',
} as const;
